/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */

plugins {
    id("java")
    id("idea")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

sourceSets {
    main {
        java {
            setSrcDirs(listOf("src"))
        }
    }
}

tasks.withType<JavaCompile> {
    destinationDirectory.set(file("build/classes"))
}

tasks.register<JavaExec>("runTrie") {
    group = "application"
    mainClass.set("ce326.hw1.HW1")
//    classpath = files("build/classes/java/main", "build/resources/main")
    classpath = files("build/classes")
//    classpath = sourceSets.main.get().runtimeClasspath
    standardInput = System.`in`
}